packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

gitChecks: false
ignoreWorkspaceRootCheck: true
minimumReleaseAgeExclude:
  - simptrad@0.3.0
shamefullyHoist: true
